language: java
jdk:
  - openjdk11
script:
  - ./mvnw clean install

services:
  - docker

jobs:
  include:
    - stage: build_java_package
      script:
        - mvn clean package

    - stage: build_docker
      script:
        - docker build -f Dockerfile -t identity:latest .
        - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
        - docker tag identity $DOCKER_HUB_USERNAME/identity
        - docker push $DOCKER_HUB_USERNAME/identity