language: java
jdk:
  - openjdk11
script:
  - ./mvnw clean install

services:
  - docker

jobs:
  include:
    - stage: build_java_package
      script:
        - mvn clean package

    - stage: build_docker
      script:
        - docker build -f Dockerfile -t identity:latest .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag identity $DOCKER_USERNAME/identity
        - docker push $DOCKER_USERNAME/identity